name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish native-keymap
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: native-keymap

        buildSteps:
          - script: npm ci
            displayName: Install dependencies

        testPlatforms:
          - name: Linux
            nodeVersions:
              - 18.17.x
          - name: MacOS
            nodeVersions:
              - 18.17.x
          - name: Windows
            nodeVersions:
              - 18.17.x

        testSteps:
          # https://github.com/nodejs/node-gyp/issues/2869
          - script: python3 -m pip install setuptools
          - script: npm ci
            displayName: Install dependencies

          - script: npm test
            displayName: Test

        apiScanSoftwareName: 'vscode-native-keymap'
        apiScanSoftwareVersion: '3.3'

        publishPackage: ${{ parameters.publishPackage }}

    policheckExclusionsFile: '$(Build.SourcesDirectory)/PoliCheckExclusions.xml'
